-- 코드를 입력하세요
SELECT
    UGU.USER_ID,
    UGU.NICKNAME,
    -- 전체 주소로 합치기
    CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) AS '전체주소',
    -- 전화번호에 하이푼 추가
    CONCAT(LEFT(UGU.TLNO, 3), '-', SUBSTRING(UGU.TLNO, 4, 4), '-', RIGHT(UGU.TLNO, 4)) AS '전화번호'
FROM
    USED_GOODS_BOARD UGB
    LEFT JOIN USED_GOODS_USER UGU
    ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY
    WRITER_ID
HAVING
    COUNT(*) >= 3
ORDER BY
    UGU.USER_ID DESC;