-- IFNULL 사용, 경기도에 위치한 창고를 출력해야함
SELECT
    WAREHOUSE_ID,
    WAREHOUSE_NAME,
    ADDRESS,
    IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM
    FOOD_WAREHOUSE
WHERE
    ADDRESS LIKE '경기도%'
ORDER BY
    WAREHOUSE_ID ASC;