-- GROUP BY, AVG, DATEDIFF, ROUND
-- DATEDIFF 사용시 -> 당일에 빌리고 반납해도 1일인데 0으로 계산 -> 계산식에 +1

SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY
    CAR_ID
HAVING
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC;