-- 각 분기를 나눠야함 -> CASE 한후 그룹화
-- 분화된 대장균 개체 수 -> ID 개수

SELECT
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
        ELSE '4Q'
    END AS QUARTER,
    COUNT(ID) AS ECOLI_COUNT
FROM
    ECOLI_DATA
GROUP BY
    QUARTER
ORDER BY
    QUARTER ASC;