-- 코드를 입력하세요
SELECT
    AI.NAME,
    AI.DATETIME
FROM
    ANIMAL_INS AI
    LEFT JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE
    -- 입양을 못 간 동물 조회
    AO.ANIMAL_ID IS NULL
ORDER BY
    AI.DATETIME
LIMIT
    3;