-- SUBSTR -> SUBSTR(바꿀 문자, 시작위치, 끝나는 위치)
SELECT
    SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY,
    COUNT(PRODUCT_ID) AS PRODUCTS
FROM
    PRODUCT
GROUP BY
    SUBSTR(PRODUCT_CODE, 1, 2)
ORDER BY
    PRODUCT_CODE ASC;