-- JOIN 사용, '2022년 10월에 작성' 조건 유의 -> LEFT 사용
SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_BOARD UGB
    INNER JOIN USED_GOODS_REPLY UGR
        ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE
    LEFT(UGB.CREATED_DATE, 7) = '2022-10'
ORDER BY
    UGR.CREATED_DATE ASC,
    UGB.TITLE;